<FrontScreen>:
    FloatLayout:
        FitImage:
            source: "C:/Users/uvais/Downloads/one.png"  # Ensure this path is correct or adjust it
            allow_stretch: True
            keep_ratio: False

        MDSpinner:
            id: spinner
            size_hint: None, None
            size: dp(46), dp(46)
            pos_hint: {'center_x': 0.5, 'center_y': 0.1}
            active: False
