
MDScreen:
<lawofattraction>:

    md_bg_color:"black"

    name:"lawofattraction"

    
    Screen:
        
        FitImage:
            size_hint_x:1
            size_hint_y:0.5
            pos_hint: { "center_x": .5, "center_y": 0.85 }
            radius:[90,90]
            source:"C:/Users/uvais/Downloads/pimg/q24.jpg"

	
	MDScrollView:
        
		MDBoxLayout:

            
            MDBoxLayout:
                
                size_hint_y:0.7
                #size_hint_x:1

                MDBoxLayout:
                    pos_hint: {  "center_y": 0.85 }
                    orientation: 'vertical'
                    size_hint_y:0.2
                    size_hint_x:1.2


                    MDCard:
                        #padding: 4
                        radius:[30]
                        #md_bg_color: "#513315"
                        md_bg_color:"black"
                        size_hint: 0.8, 0.8
                        #size: "10dp", "90dp"
                        pos_hint: {"top": 1, "right": 0.95}
                        MDRelativeLayout:

                            MDIconButton:
                                icon: "clock-time-eight"
                                pos_hint: {"top": 0.59, "right": 0.39}
                                icon_size:"20dp"
                                icon_color:"white"
                                #md_bg_color:"black"
                            

                            MDLabel:
                                id: label
                                text: "10-20"
                                #adaptive_size: True
                                color: "#513315"
                                font_style:"H6"

                                pos: "40dp", "18dp"
                                bold: True

                            MDLabel:
                                id: label
                                text: "Minutes"
                                adaptive_size: True
                                color: "#513315"
                                pos: "50dp", "20dp"
                                
                        
                MDBoxLayout:
                    
                    pos_hint: {  "center_y": 0.85 }
                    orientation: 'vertical'
                    size_hint_y:0.2
                    size_hint_x:1.2
                    MDCard:
                        #padding: 4
                        radius:[30]
                        md_bg_color: "black"

                        size_hint: 0.8, 0.8
                        
                        pos_hint: {"top": 0.1, "right": 0.85}
                        MDRelativeLayout:
                            MDIconButton:
                                adaptive_size: True
                                icon: "list-status"
                                pos_hint: {"top": 0.52, "right": 0.45}
                                icon_size:"20dp"
                                icon_color:"#513315"
                                #color:"black"
                            MDLabel:
                                id: label
                                text: "3"
                                #adaptive_size: True
                                color: "#513315"
                                font_style:"H6"

                                pos: "60dp", "18dp"
                                bold: True
                            MDLabel:
                                id: label
                                text: "tasks"
                                #adaptive_size: True
                                color: "#513315"

                                #pos: "40dp", "0dp"
                                pos_hint: {"top": 0.8, "right": 1.4}
                            MDLabel:
                                id: label
                                text: "Overviews"
                                #adaptive_size: True
                                color: "#513315"
                                bold:True
                                #pos: "40dp", "0dp"
                                pos_hint: {"top": 0.2, "right": 0}
                            
                

    MDScrollView:
        MDBoxLayout:
            orientation: 'vertical'
            size_hint_y:3.3
            
            MDRelativeLayout:
                
                MDBoxLayout:
                    md_bg_color:"black"
                    #padding:5
                    size_hint_y:0.58
                    size_hint_x:1
                    spacing:10
                    pos_hint: {"top": 0.81}
                    MDCard:

                        size_hint_y:0.4
                        pos_hint: {"top": 1}
                        radius:[30]
                        MDRelativeLayout:
                            FitImage:
                                source:"C:/Users/uvais/Downloads/pimg/law11.jpg"
                                radius:[30]
                            MDLabel:
                                padding:10
                                text:"What is the Law Of Attraction"
                                font_style:"H3"
                                pos_hint:{"top":1.25}
                                bold:True
                                color:"white"
                            MDLabel:
                                text:"The Law of Attraction is a powerful universal principle based on the belief that our thoughts, feelings, and beliefs shape our reality. Simply put, like attracts like. When you focus on positive thoughts and feelings, you attract positive experiences into your life. Likewise, negative thoughts can bring negative outcomes.By harnessing the power of your mind, you can manifest the life you desire. Whether it’s achieving personal goals, building wealth, attracting love, or finding happiness, the Law of Attraction invites you to align your thoughts and actions with your deepest desires."
                                pos_hint: {"top": 0.8, "right": 1.01}
                                font_style:"Subtitle2"
                                color:"white"
                                bold:True
                                padding:5
                        
                MDBoxLayout:
                   # md_bg_color:"red"
                    pos_hint:{"top":0.56}
                    size_hint_y:0.2
                    MDScrollView:
                        #md_bg_color:"blue"
                        MDBoxLayout:
                            md_bg_color:"black"
                            size_hint_y:8
                            radius:[30]
                            padding:10
                            MDRelativeLayout:
                                FitImage
                                    source:"https://i.pinimg.com/736x/af/e1/48/afe1484d2b4a00cc1c9c2f130f258580.jpg"
                                    size_hint_y:0.2
                                    pos_hint:{"top":1.05}
                                    radius:[30]
                                FitImage
                                    source:"C:/Users/uvais/Downloads/pimg/q27.jpg"
                                    
                                    pos_hint:{"top":0.9}
                                    radius:[30]
                                MDLabel:
                                    text:"Things you should know in Law Of Attraction"
                                    font_style:"H3"

                                    pos_hint:{"top":1.45}
                                    bold:True
                                    color:"#ca9f77"

                                MDLabel:
                                    text:"1. Your Thoughts Create Your Reality"
                                    font_style:"H6"
                                    pos_hint:{"top":1.37}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"• What It Means:"
                                    font_style:"Subtitle1"
                                    pos_hint:{"top":1.353}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"Your dominant thoughts shape your experiences. Positive thoughts attract positive outcomes, while negative thoughts attract challenges"
                                    font_style:"Subtitle2"
                                    pos_hint:{"top":1.338}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"• Example:"
                                    font_style:"Subtitle1"
                                    pos_hint:{"top":1.32}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"If you constantly think, 'I always fail,' you are likely to encounter more situations where you struggle. But if you think, 'I am capable and successful,' you’ll start noticing opportunities to thrive."
                                    font_style:"Subtitle2"
                                    pos_hint:{"top":1.303}
                                    padding:10
                                    color:"white"
                                
                                MDLabel:
                                    text:"__________________________"
                                    font_style:"H6"
                                    pos_hint:{"top":1.288}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"2. Frequency and Vibration Matter"
                                    font_style:"H6"
                                    pos_hint:{"top":1.273}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"• What It Means:"
                                    font_style:"Subtitle1"
                                    pos_hint:{"top":1.256}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"Everything in the universe, including your thoughts and emotions, has an energy frequency. High-frequency emotions like gratitude, joy, and love attract positive experiences. Low-frequency emotions like fear, anger, and sadness attract negativity."
                                    font_style:"Subtitle2"
                                    pos_hint:{"top":1.234}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"• Example:"
                                    font_style:"Subtitle1"
                                    pos_hint:{"top":1.21}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"If you’re constantly angry about your financial situation, you’ll continue to attract more reasons to feel stressed about money. Shifting your frequency to gratitude for what you have opens doors for financial abundance.."
                                    font_style:"Subtitle2"
                                    pos_hint:{"top":1.19}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"__________________________"
                                    font_style:"H6"
                                    pos_hint:{"top":1.17}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"3. Feelings Amplify Manifestation"
                                    font_style:"H6"
                                    pos_hint:{"top":1.15}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"• What It Means:"
                                    font_style:"Subtitle1"
                                    pos_hint:{"top":1.135}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"The emotions behind your thoughts give them power. Feeling happy, grateful, or excited as if your desire is already fulfilled helps you manifest it faster."
                                    font_style:"Subtitle2"
                                    pos_hint:{"top":1.12}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"• Example:"
                                    font_style:"Subtitle1"
                                    pos_hint:{"top":1.1}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"If you want a dream job, imagine the joy and pride you’ll feel walking into that office. Feel those emotions now to align with the energy of your goal."
                                    font_style:"Subtitle2"
                                    pos_hint:{"top":1.084}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"__________________________"
                                    font_style:"H6"
                                    pos_hint:{"top":1.07}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"4. Eliminate Doubt"
                                    font_style:"H6"
                                    pos_hint:{"top":1.055}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"• What It Means:"
                                    font_style:"Subtitle1"
                                    pos_hint:{"top":1.046}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"Doubt creates resistance and blocks manifestation. You must trust that what you desire is possible and on its way to you.."
                                    font_style:"Subtitle2"
                                    pos_hint:{"top":1.028}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"• Example:"
                                    font_style:"Subtitle1"
                                    pos_hint:{"top":1.01}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"Instead of thinking, 'What if it doesn’t work?' believe, 'The universe is working in my favor, even if I can’t see it yet."
                                    font_style:"Subtitle2"
                                    pos_hint:{"top":0.995}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"__________________________"
                                    font_style:"H6"
                                    pos_hint:{"top":0.98}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"5. Gratitude is Key"
                                    font_style:"H6"
                                    pos_hint:{"top":0.97}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"• What It Means:"
                                    font_style:"Subtitle1"
                                    pos_hint:{"top":0.96}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"Being thankful for what you already have raises your vibration and attracts more things to be grateful for."
                                    font_style:"Subtitle2"
                                    pos_hint:{"top":0.945}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"• Example:"
                                    font_style:"Subtitle1"
                                    pos_hint:{"top":0.929}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"Start or end your day by listing three things you’re grateful for. This shifts your focus from lack to abundance.."
                                    font_style:"Subtitle2"
                                    pos_hint:{"top":0.915}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"__________________________"
                                    font_style:"H6"
                                    pos_hint:{"top":0.905}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"6. Take Inspired Action"
                                    font_style:"H6"
                                    pos_hint:{"top":0.89}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"• What It Means:"
                                    font_style:"Subtitle1"
                                    pos_hint:{"top":0.88}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"While visualization and affirmations are powerful, you must take actions aligned with your goals. The universe meets you halfway when you make an effort."
                                    font_style:"Subtitle2"
                                    pos_hint:{"top":0.86}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"• Example:"
                                    font_style:"Subtitle1"
                                    pos_hint:{"top":0.843}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"If you want to improve your health, visualize yourself as fit and strong, but also take steps like eating healthy and exercising regularly."
                                    font_style:"Subtitle2"
                                    pos_hint:{"top":0.827}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"__________________________"
                                    font_style:"H6"
                                    pos_hint:{"top":0.813}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"7. Focus on What You Want, Not What You Don’t Want"
                                    font_style:"H6"
                                    pos_hint:{"top":0.795}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"• What It Means:"
                                    font_style:"Subtitle1"
                                    pos_hint:{"top":0.78}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"The Law of Attraction doesn’t differentiate between what you want and don’t want—it amplifies your focus."
                                    font_style:"Subtitle2"
                                    pos_hint:{"top":0.763}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"• Example:"
                                    font_style:"Subtitle1"
                                    pos_hint:{"top":0.74}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"Instead of thinking, I don’t want to be broke, focus on, I am financially abundant."
                                    font_style:"Subtitle2"
                                    pos_hint:{"top":0.725}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"__________________________"
                                    font_style:"H6"
                                    pos_hint:{"top":0.711}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"8. Let Go of Negativity"
                                    font_style:"H6"
                                    pos_hint:{"top":0.694}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"• What It Means:"
                                    font_style:"Subtitle1"
                                    pos_hint:{"top":0.679}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"Harboring negative emotions like resentment, jealousy, or fear lowers your frequency and blocks manifestation."
                                    font_style:"Subtitle2"
                                    pos_hint:{"top":0.664}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"• Example:"
                                    font_style:"Subtitle1"
                                    pos_hint:{"top":0.65}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"If you’re jealous of someone’s success, shift your mindset to admiration and use it as inspiration for your journey."
                                    font_style:"Subtitle2"
                                    pos_hint:{"top":0.635}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"__________________________"
                                    font_style:"H6"
                                    pos_hint:{"top":0.62}
                                    padding:10
                                    color:"white"
                                MDLabel:
                                    text:"Summary"
                                    font_style:"H5"
                                    pos_hint:{"top":0.6}
                                    padding:10
                                    color:"#ca9f77"
                                MDLabel:
                                    text:"To make the most of the Law of Attraction:"
                                    font_style:"Subtitle1"
                                    pos_hint:{"top":0.58}
                                    padding:10
                                    color:"#ca9f77"
                                MDLabel:
                                    text:"• Maintain positive thoughts and high frequency emotions."
                                    font_style:"Subtitle2"
                                    pos_hint:{"top":0.56}
                                    padding:10
                                    color:"#ca9f77"
                                MDLabel:
                                    text:"• Believe in the process and eliminate doubt.:"
                                    font_style:"Subtitle2"
                                    pos_hint:{"top":0.545}
                                    padding:10
                                    color:"#ca9f77"
                                MDLabel:
                                    text:"• Focus on what you want and take aligned actions."
                                    font_style:"Subtitle2"
                                    pos_hint:{"top":0.531}
                                    padding:10
                                    color:"#ca9f77"
                                MDLabel:
                                    text:"• Practice gratitude and patience.."
                                    font_style:"Subtitle2"
                                    pos_hint:{"top":0.52}
                                    padding:10
                                    color:"#ca9f77"
                MDBoxLayout:
                    #md_bg_color:"black"
                    size_hint_y:0.5
                    pos_hint:{"top":0.6}
                    MDCard:
                        md_bg_color:"black"
                        size_hint_y:0.5
                        radius:[30]
                        padding:10
                        MDRelativeLayout:
                            
                            
                            MDLabel:
                                text:"How This App Helps You"
                                font_style:"H4"
                                color:"white"
                                pos_hint:{"top":1.4,"right":1.05}
                                padding:10
                                bold:True
                                color:"#2c7b72"
                            
                            MDLabel:
                                text:"This app is designed to make practicing the Law of Attraction simple and effective. With features like:"
                                font_style:"Subtitle1"
                                bold:True
                                pos_hint:{"top":1.15}
                                padding:10
                                color:"white"
                            MDLabel:
                                text:"• Personalized affirmations to keep you inspired.\n\n\n• Guided visualizations to help you focus on your goals.\n\n\n• Journaling tools to track your progress and reflect on your growth."
                                font_style:"Subtitle2"
                                bold:True
                                pos_hint:{"top":0.87}
                                padding:10
                          
                            
                            MDLabel:
                                text:"Start your journey today and unlock the incredible power within you!"
                                font_style:"Subtitle1"
                                bold:True
                                pos_hint:{"top":0.63}
                                padding:10
                                color:"white"
                        
                            MDIconButton:
                                icon:"arrow-left-circle"

                                icon_size:"30dp"
                                pos_hint:{"top":3.67,"right":0.17}
                                icon_color:"white"
                                on_press: root.manager.current = 'mainscreen' 
                MDBoxLayout:
                    pos_hint:{"top":0.1}
                    spacing:2
                    orientation: 'vertical'
                    size_hint_y: 0.3
                    size_hint_x:1
                    MDScrollView:
                        do_scroll_y:False
                        radius: [20]
                        MDBoxLayout:
                            radius: [20]
                            size_hint_x:2
                            size_hint_y:0.35
                            padding:10
                            spacing:5
                            MDCard:
                                ripple_behavior: True
                                size_hint_y:1
                                size_hint_x:0.5
                                md_bg_color:"red"
                                radius:[30]
                                MDRelativeLayout:
                                    FitImage:
                                        source:"C:/Users/uvais/Downloads/pimg/lawcard.jpg"
                                        radius:[20]
                            MDCard:
                                ripple_behavior: True
                                size_hint_y:1
                                size_hint_x:0.5
                                md_bg_color:"red"
                                radius:[30]
                                on_press: root.manager.current = 'visualization_tech'
                                MDRelativeLayout:
                                    FitImage:
                                        source:"C:/Users/uvais/Downloads/pimg/lawcard1.jpg"
                                        radius:[20]
                                
                            MDCard:
                                ripple_behavior: True
                                size_hint_y:1
                                size_hint_x:0.5
                                md_bg_color:"red"
                                radius:[30]
                                MDRelativeLayout:
                                    FitImage:
                                        source:"C:/Users/uvais/Downloads/pimg/lawcard2.jpg"
                                        radius:[20]
                                    
                            MDCard:
                                ripple_behavior: True
                                
                                size_hint_y:1
                                size_hint_x:0.5
                                md_bg_color:"red"
                                radius:[30]
                                MDRelativeLayout:
                                    FitImage:
                                        source:"C:/Users/uvais/Downloads/pimg/lawcard3.jpg"
                                        radius:[20]
                            

<visualization_tech>:
    on_enter:root.check_file()
    MDScrollView:      
        MDBoxLayout:
            orientation: 'vertical'
            size_hint_y:3.9
            #size_hint_x:1
            md_bg_color:"#fff2e6"
            MDRelativeLayout:
                MDBoxLayout:
                    #md_bg_color:"red"
                    #padding:20
                    size_hint: 1.2, 0.17
                    pos_hint:{"right":1.09}
                    radius:[800]

                    MDCard:
                        #md_bg_color:"#513315"
                        radius:[700]
                        #line_width:30
                        #line_color: "#513315"
                        size_hint: 9, 1.2
                        pos_hint:{"top":6.2,"right":1.6}
                        MDRelativeLayout:
                            FitImage:
                                source:"https://i.pinimg.com/736x/d4/6e/b0/d46eb04284df18358562cc19cd9af992.jpg"
                                radius:[255]
                                pos_hint:{"top":1.3}
                                size_hint_y:1.3
                            MDLabel:
                                text:"Imagine is all you  need"
                                bold:True
                                font_style:"H6"
                                pos_hint:{"top":0.7,"right":1.2}
                                #halign:"center"
                                color:"white"
                            MDCard:
                                size_hint:0.24,0.12
                                md_bg_color:"#6600ff"
                                pos_hint:{"top":0.4,"right":0.52}
                                radius:[22]
                                id: button
                                on_release: root.toggle_tap_target("1")
                                MDRelativeLayout:
                                    MDLabel:
                                        text:"Imagine"
                                        color:"black"
                                        halign:"center"
                                        font_style:"Caption"
                            MDCard:
                                size_hint:0.24,0.12
                                pos_hint:{"top":0.4,"right":0.79}
                                radius:[22]
                                md_bg_color:"#6600ff"
                                id: button2
                                on_release: root.toggle_tap_target("2")
                                MDRelativeLayout:
                                    MDLabel:
                                        text:"Manifest"
                                        color:"black"
                                        halign:"center"
                                        font_style:"Caption"
                            MDIconButton:
                                icon:"arrow-left-circle"
                                pos_hint:{"top":0.68,"right":0.23}
                                icon_size:"20dp"
                                md_bg_color:"#6600ff"
                                on_press: root.manager.current = 'lawofattraction'
                            MDIconButton:
                                icon:"file-edit"
                                pos_hint:{"top":0.7,"right":0.92}
                                icon_size:"20dp"
                                #md_bg_color:"#6600ff"
                                on_press: root.manager.current = 'loaform'
                            MDLabel:
                                
                                text:"Visualization with "
                                bold:True
                                padding:20
                                color:"#6600ff"
                                font_style:"H5"
                                pos_hint:{"right":1.25,"top":1.15}
                            MDLabel:
                                
                                text:"Affirmations "
                                bold:True
                                padding:20
                                color:"white"
                                font_style:"H5"
                                pos_hint:{"right":1.25,"top":1.08}
                            

                MDBoxLayout:
                    
                    size_hint_y:0.03
                    size_hint_x:1
                    
                    pos_hint: {"top":0.84}
                    spacing: "15dp"
                    padding:10
                    MDCard:
                        md_bg_color:"white"
                        size_hint_x:1
                        size_hint_y:1
                        radius:[22]
                        line_width:1
                        line_color:"#6600ff"
                        padding:10
                        pos_hint:{"top":1}
                        MDRelativeLayout:
                            
                            MDChip:
                                text: "Overview"
                                group: "x"
                                on_release: root.switch_screen("overview")
                                pos_hint:{"top":1,"right":0.43}
                                spacing: "15dp"
                                md_bg_color:"#fff2e6"
                                text_color:"black"
                                padding:5
                            MDChip:
                                text: "Techniques"
                                group: "x"
                                on_release: root.switch_screen("techniques")
                                pos_hint:{"top":1,"right":0.9}
                                md_bg_color:"#6600ff"
                


                # Lower dynamic part (switchable content)
                MDBoxLayout:
                    size_hint_y: 0.8
                    pos_hint:{"top":0.8}
                    
                    MDScreenManager:
                        id: screen_manager
                        MDScreen:
                            name: "overview"
                            
                            MDBoxLayout:
                                md_bg_color:"white"
                                orientation: "vertical"
                                spacing: "10dp"
                                size_hint_y:1.7
                                padding: "5dp"
                                radius:[20]
                                MDRelativeLayout:
                                    MDLabel:
                                        text: "Introduction"
                                        font_style: "H5"
                                        color: "#513315"

                                        pos_hint:{"top":1.085}
                                    FitImage:
                                        source:"https://mir-s3-cdn-cf.behance.net/project_modules/fs/6bd9ad193614011.65ef0ed157a38.jpg"
                                        radius:[10]
                                        size_hint_y:0.1
                                        pos_hint:{"top":0.47}
                                    MDBoxLayout:
                                        size_hint_x:1
                                        size_hint_y:0.12
                                        md_bg_color:"#fff2e6"
                                        pos_hint:{"top":0.58}
                                        MDRelativeLayout:
                                            

                                            MDLabel:
                                                padding:10
                                                text:"Visualization with affirmations is a practice that combines two powerful techniques:."
                                                color:"black"
                                                font_style:"Subtitle1"
                                                pos_hint:{"top":1.35}
                                                bold:True
                                            MDLabel:
                                                padding:10
                                                text:"•  Visualization: Mentally picturing yourself achieving your goals or living your desired reality."
                                                color:"black"
                                                font_style:"Subtitle2"
                                                pos_hint:{"top":1.14}
                                            MDLabel:
                                                padding:10
                                                text:"•  Affirmations: Positive, empowering statements that reinforce your beliefs and encourage self-confidence."
                                                color:"black"
                                                font_style:"Subtitle2"
                                                pos_hint:{"top":0.95}
                                            MDLabel:
                                                padding:10
                                                text:"When used together, these tools create a focused and intentional mindset that aligns your thoughts, emotions, and actions with your goals. It’s like programming your mind for success by repeatedly experiencing your desired outcomes mentally and emotionally."
                                                color:"black"
                                                font_style:"Subtitle2"
                                                pos_hint:{"top":0.73}
                                    
                                    
                                    MDScrollView:
                                        bar_width: dp(10)
                                        pos_hint:{"top":0.36}
                                        size_hint_y:0.13
                                        #size_hint_x:3
                                        #md_bg_color:"black"
                                        #do_scroll_y:False
                                        MDBoxLayout:
                                            size_hint_x:5.1
                                            do_scroll_y:False
                                            size_hint_y:1
                                            pos_hint:{"top":0.2}
                                            #md_bg_color:"red"
                                            MDCard:

                                                size_hint_x:0.06
                                                size_hint_y:1
                                                md_bg_color:"black"
                                                #pos_hint:{"top":1}
                                                MDRelativeLayout:
                                                    MDLabel:
                                                        padding:5
                                                        text:"How Does It Work"
                                                        color:"white"
                                                        font_style:"H1"
                                                        pos_hint:{"right":1,"top":1}
                                                        size_hint_x:1
                                                        color:"#6600ff"
                                            MDCard:
                                                md_bg_color:"black"
                                                size_hint:0.06,1
                                                pos_hint:{"right":1}
                                                padding:10
                                                MDRelativeLayout:
                                                    MDLabel:
                                                        
                                                        text:"1. Activating the Subconscious Mind:"
                                                        color:"white"
                                                        font_style:"H6"
                                                        pos_hint:{"top":1.3}
                                                        bold:"True"
                                                    MDLabel:
                                                        padding:4
                                                        text:" • Visualization helps create a vivid mental image of your goals. The brain cannot easily distinguish between real and imagined experiences, which means visualizing success can feel as real as actual success.."
                                                        color:"white"
                                                        font_style:"Subtitle2"
                                                        pos_hint:{"top":1}
                                                    MDLabel:
                                                        padding:4
                                                        text:"• Affirmations reprogram your subconscious mind by replacing limiting beliefs with empowering ones."
                                                        color:"white"
                                                        font_style:"Subtitle2"
                                                        pos_hint:{"top":0.7}
                                            MDCard:
                                                md_bg_color:"black"
                                                size_hint:0.06,1
                                                padding:10
                                                MDRelativeLayout:
                                                    MDLabel:
                                                        text:"2. Aligning Thoughts, Emotions, and Actions:"
                                                        color:"white"
                                                        font_style:"H6"
                                                        pos_hint:{"top":1.3}
                                                        bold:"True"
                                                    MDLabel:
                                                        padding:4
                                                        text:" • When you visualize, you not only see your success but also feel the emotions associated with it (e.g., happiness, confidence, pride)."
                                                        color:"white"
                                                        font_style:"Subtitle2"
                                                        pos_hint:{"top":1}
                                                    MDLabel:
                                                        padding:4
                                                        text:"• These positive emotions reinforce your belief in achieving your goals and encourage actions aligned with your vision."
                                                        color:"white"
                                                        font_style:"Subtitle2"
                                                        pos_hint:{"top":0.7,"right":1}
                                                
                                            MDCard:
                                                md_bg_color:"black"
                                                size_hint:0.06,1
                                                padding:10
                                                MDRelativeLayout:
                                                    MDLabel:
                                                        text:"3. Law of Attraction in Action:"
                                                        color:"white"
                                                        font_style:"H5"
                                                        pos_hint:{"top":1.3}
                                                        bold:"True"
                                                    MDLabel:
                                                        padding:4
                                                        text:" • By repeatedly focusing on what you want and affirming your ability to achieve it, you attract opportunities, resources, and circumstances that help you manifest your desires."
                                                        color:"white"
                                                        font_style:"Subtitle1"
                                                        pos_hint:{"top":0.9}
                                                    
                                                
                                            MDCard:
                                                md_bg_color:"black"
                                                size_hint:0.06,1
                                                padding:10
                                                MDRelativeLayout:
                                                    MDLabel:
                                                        text:"5. Boosting Emotional and Mental State:"
                                                        color:"white"
                                                        font_style:"H5"
                                                        pos_hint:{"top":1.3}
                                                        bold:"True"
                                                    MDLabel:
                                                        padding:4
                                                        text:" • Repeating affirmations while visualizing helps you stay motivated, confident, and resilient, even when faced with challenges."
                                                        color:"white"
                                                        font_style:"Subtitle1"
                                                        pos_hint:{"top":0.9}
                                                    
                                                
                                    MDScrollView:
                                        bar_width: dp(10)
                                        size_hint_y:0.11
                                        #md_bg_color:"blue"
                                        pos_hint:{"top":0.22}           
                                        MDBoxLayout:
                                            size_hint_y:4
                                            size_hint_x:1
                                            md_bg_color:"#fff2e6"
                                            MDRelativeLayout:
                                                FitImage:
                                                    source:"C:/Users/uvais/Downloads/pimg/frame1.png"
                                                    size_hint_x:1
                                                    size_hint_y:0.4
                                                    
                                                    pos_hint:{"top":1}
                                                FitImage:
                                                    source:"C:/Users/uvais/Downloads/pimg/seatedw.png"
                                                    #size_hint_x:1
                                                    size_hint_y:0.12
                                                    
                                                    pos_hint:{"top":0.12,"right":1}
                                                MDLabel:
                                                    text:"Steps for Visualization with Affirmations technique."
                                                    font_style:"H3"
                                                    pos_hint:{"top":1.57}
                                                    color:"black"
                                                    bold:True
                                                    padding:10
                                                    size_hint_x:1
                                                    size_hint_y:1.4
                                                MDLabel:
                                                    text:"Step 1: Click to See Your Affirmations."
                                                    font_style:"H6"
                                                    pos_hint:{"top":1.23}
                                                    color:"black"
                                                    bold:True
                                                    padding:10
                                                MDLabel:
                                                    text:"Start by reviewing your personalized affirmations"
                                                    font_style:"Subtitle1"
                                                    pos_hint:{"top":1.19}
                                                    color:"black"
                                                    padding:10
                                                MDLabel:
                                                    text:"• These affirmations are crafted based on your goals and the form you completed earlier.\n\n• Read them silently or aloud, and feel their meaning as you go through them."
                                                    font_style:"Subtitle2"
                                                    pos_hint:{"top":1.14}
                                                    color:"black"
                                                    padding:10
                                                MDLabel:
                                                    text:"Step 2: Choose Music to Match Your Mood."
                                                    font_style:"H6"
                                                    pos_hint:{"top":1.08}
                                                    color:"black"
                                                    bold:True
                                                    padding:10
                                                MDLabel:
                                                    text:"Music can amplify your visualization experience by enhancing your emotions and focus."
                                                    font_style:"Subtitle1"
                                                    pos_hint:{"top":1.03}
                                                    color:"black"
                                                    padding:10
                                                MDLabel:
                                                    text:"• Select a calming track or background music from the app's library.\n\n• Choose music that resonates with your goals, such as relaxing nature sounds, instrumental tones, or guided affirmation tracks."
                                                    font_style:"Subtitle2"
                                                    pos_hint:{"top":0.96}
                                                    color:"black"
                                                    padding:10
                                                MDLabel:
                                                    text:"Step 3: Click to Generate Visualization with Affirmations."
                                                    font_style:"H6"
                                                    pos_hint:{"top":0.89}
                                                    color:"black"
                                                    bold:True
                                                    padding:10
                                                MDLabel:
                                                    text:"Once you've reviewed your affirmations and chosen your music."
                                                    font_style:"Subtitle1"
                                                    pos_hint:{"top":0.84}
                                                    color:"black"
                                                    padding:10
                                                MDLabel:
                                                    text:"1. Click the 'Generate Visualization' button in the app."
                                                    font_style:"Subtitle2"
                                                    pos_hint:{"top":0.8}
                                                    color:"black"
                                                    padding:10
                                                MDLabel:
                                                    text:"2.Follow the guided instructions to begin your visualization session."
                                                    font_style:"Subtitle2"
                                                    pos_hint:{"top":0.76}
                                                    color:"black"
                                                    padding:10
                                                MDLabel:
                                                    text:"• The app will prompt you to close your eyes, relax, and imagine your goals as if they’re already achieved.\n\n• Visual cues or animations may be included to help you focus."
                                                    font_style:"Caption"
                                                    pos_hint:{"top":0.71}
                                                    color:"black"
                                                    padding:10
                                                MDLabel:
                                                    text:"End with Gratitude"
                                                    font_style:"H6"
                                                    pos_hint:{"top":0.66}
                                                    color:"black"
                                                    bold:True
                                                    padding:10
                                                MDLabel:
                                                    text:"Once your session is complete, take a moment to feel gratitude for what you already have and for what’s coming into your life. Gratitude strengthens your belief and enhances your frequency."
                                                    font_style:"Subtitle1"
                                                    pos_hint:{"top":0.6}
                                                    color:"black"
                                                    
                                                    padding:10

                                    MDScrollView:
                                        pos_hint:{"top":0.1}
                                        size_hint_y:0.1
                                        bar_width: dp(10)
                                        do_scroll_y:False
                                        MDBoxLayout:
                                            md_bg_color:"#fff2e6"
                                            size_hint_x:4
                                            do_scroll_y:False
                                            size_hint_y:1.4
                                            pos_hint:{"top":0.24}
                                            #md_bg_color:"red"
                                            MDCard:
                                                md_bg_color:"#fff2e6"
                                                size_hint_x:1
                                                size_hint_y:1
                                                MDRelativeLayout:
                                                    Image:
                                                        source:"C:/Users/uvais/Downloads/pimg/whale1.png"
                                                        size_hint_y:0.7
                                                        size_hint_x:0.8
                                                        pos_hint:{"top":0.75}
                                                        
                                                    MDLabel:
                                                        text:"Night and Morning Are the Best Times to Manifest"
                                                        font_style:"H4"
                                                        bold:True
                                                        padding:10
                                                        pos_hint:{"top":1.33}
                                                        color:"black"
                                                        
                                                    MDLabel:
                                                        color:"black"
                                                        text:"• The times just before falling asleep and right after waking up are the most effective for manifestation. Here’s why"
                                                        font_style:"Subtitle1"
                                                        bold:True
                                                        padding:10
                                                        pos_hint:{"top":1.05}
                                                        
                                                    

                                                    
                                           
                                            MDCard:
                                                md_bg_color:"#fff2e6"
                                                size_hint_x:1
                                                size_hint_y:1
                                                MDRelativeLayout:
                                                    MDLabel:
                                                        color:"black"
                                                        text:"1. Your Mind is in a Relaxed State (Theta Brainwave State)"
                                                        font_style:"H6"
                                                        bold:True
                                                        padding:10
                                                        pos_hint:{"top":1.4}
                                                    MDLabel:
                                                        color:"black"
                                                        text:"• During these times, your brain operates in a theta brainwave state, which is a deeply relaxed, meditative state.\n\n• This state allows your subconscious mind to absorb affirmations and visualizations more effectively, as the conscious mind’s critical filter is less active."
                                                        font_style:"Subtitle1"
                                                        padding:10
                                                        pos_hint:{"top":1.08}
                                            MDCard:
                                                md_bg_color:"#fff2e6"
                                                size_hint_x:1
                                                size_hint_y:1
                                                MDRelativeLayout:
                                                    MDLabel:
                                                        color:"black"
                                                        text:"2. Programming Your Subconscious Mind at Night"
                                                        font_style:"H6"
                                                        bold:True
                                                        padding:10
                                                        pos_hint:{"top":1.4}
                                                    MDLabel:
                                                        color:"black"
                                                        text:"• Before sleep, your subconscious mind continues to process thoughts and emotions for hours.\n\n• Listening to affirmations or visualizing during this time ensures your subconscious is focused on your goals while you sleep.\n\n• This programming creates a positive feedback loop, aligning your thoughts and energy with what you desire."
                                                        font_style:"Subtitle2"
                                                        padding:10
                                                        pos_hint:{"top":1.1}
                                            MDCard:
                                                md_bg_color:"#fff2e6"
                                                size_hint_x:1
                                                size_hint_y:1
                                                MDRelativeLayout:
                                                    MDLabel:
                                                        color:"black"
                                                        text:"3. Setting a Positive Tone in the Morning"
                                                        font_style:"H6"
                                                        bold:True
                                                        padding:10
                                                        pos_hint:{"top":1.4}
                                                    MDLabel:
                                                        color:"black"
                                                        text:"• The first few moments after waking up set the tone for your day.\n\n• Morning affirmations and visualizations help you start your day with a high-frequency mindset, such as gratitude, positivity, and focus.\n\n• This positive start helps you attract opportunities and remain aligned with your goals throughout the day."
                                                        font_style:"Subtitle2"
                                                        padding:10
                                                        pos_hint:{"top":1.1}

                                            
                        MDScreen:
                            name: "techniques"
                            on_enter:root.generate_affirmation("2")
                            MDBoxLayout:

                                orientation: "vertical"
                                radius:[20]
                                spacing: "10dp"
                                padding: "10dp"
                                MDRelativeLayout:
                                    MDBoxLayout:
                                        size_hint_y:0.35
                                        #md_bg_color:"#6600ff"
                                        pos_hint:{"top":1}
                                        radius:[30]
                                        MDRelativeLayout:
                                            id:user_name
                                            FitImage:
                                                source:"C:/Users/uvais/Downloads/pimg/clouds.png"
                                                size_hint_y:1
                                                
                                                #radius:[20,20,20,20]      
                                            
                                           

                                            MDLabel:
                                                color:"black"
                                                text:"1. Step"
                                                padding:10
                                                font_style:"H5"
                                                pos_hint:{"top":1.25}
                                                bold:True
                                            MDLabel:
                                                color:"black"
                                                text:" we create some affirmation accourding to your Goal,Challenge and Desired "
                                                font_style:"Subtitle1"
                                                pos_hint:{"top":1.15}
                                                padding:10
                                                bold:True
                                            MDRectangleFlatButton:
                                                text:"click to generate "
                                                pos_hint:{"top":0.55,"right":0.7}
                                                text_color: "black"
                                                line_color: "black"
                                                on_release:root.generate_affirmation("1")
                                            MDLabel:
                                                color:"black"
                                                text:" Here is your Affirmations  "
                                                font_style:"H6"
                                                pos_hint:{"top":0.93}
                                                padding:10
                                                bold:True
                                    MDBoxLayout:
                                        size_hint_y:0.12
                                        pos_hint:{"top":0.74}
                                       # md_bg_color:"red"
                                        MDScrollView:
                                            bar_width: dp(10)
                                            MDBoxLayout:
                                                id:affirmations_box
                                                size_hint_y:5
                                                orientation:"vertical"
                                                padding:5
                                                #md_bg_color:"blue"
                                                MDRelativeLayout:
                                                    id:generated_affirmation
                                                    
                                    MDBoxLayout:
                                        size_hint_y:0.3
                                        md_bg_color:"#6600ff"
                                        pos_hint:{"top":0.6}
                                        radius:[20]
                                        #padding:10
                                        spacing:10
                                        MDRelativeLayout:
                                            padding:10
                                            FitImage
                                                #source:"https://i.pinimg.com/736x/b4/55/3b/b4553bb9aef1fcf5146c67dcfbf08afb.jpg"
                                                radius:[20]
                                        
                                            MDLabel:
                                                text:"2. Step "
                                                font_style:"H5"
                                                pos_hint:{"top":1.2}
                                                bold:True
                                                color:"black"
                                                padding:10
                                            MDLabel:
                                                text:"Select the sounds accourding to you "
                                                font_style:"H4"
                                                pos_hint:{"top":1.37}
                                                bold:True
                                                color:"black"
                                                padding:10
                                            MDLabel:
                                                text:"These sounds help you while you are manifesting "
                                                font_style:"H6"
                                                pos_hint:{"top":1.12}
                                                bold:True
                                                padding:10
                                                color:"black"
                                            MDCard:
                                                size_hint_y:0.2
                                                size_hint_x:0.48
                                                pos_hint:{"top":0.51,"right":0.49}
                                                md_bg_color:"white"
                                                on_press: root.play_background_sound("1")
                                                padding:5
                                                radius:[30]
                                                MDRelativeLayout:
                                                    FitImage:
                                                        source:"https://i.pinimg.com/736x/99/fe/39/99fe397be9721005e1f07d54c4686e39.jpg"
                                                        radius:[30]
                                                    MDLabel:
                                                        text:"Soft Piano Sound"
                                                        font_style:"Subtitle1"
                                                        bold:True
                                                        padding:10
                                                        pos_hint:{"top":0.74}
                                                        color:"white"
                                            MDCard:
                                                size_hint_y:0.2
                                                size_hint_x:0.48
                                                pos_hint:{"top":0.51,"right":0.99}
                                                md_bg_color:"white"
                                                on_press: root.play_background_sound("2")
                                                radius:[30]
                                                padding:5
                                                MDRelativeLayout:
                                                    FitImage:
                                                        source:"https://i.pinimg.com/736x/99/c6/1e/99c61e58035f952129b32f48dfc4873f.jpg"
                                                        radius:[30]
                                                    MDLabel:
                                                        text:"Fireplace Sound"
                                                        font_style:"Subtitle1"
                                                        bold:True
                                                        padding:10
                                                        pos_hint:{"top":0.68}
                                            MDCard:
                                                size_hint_y:0.2
                                                size_hint_x:0.48
                                                pos_hint:{"top":0.3,"right":0.99}
                                                md_bg_color:"white"
                                                on_press: root.play_background_sound("3")
                                                radius:[30]
                                                padding:5
                                                MDRelativeLayout:
                                                    FitImage:
                                                        source:"https://i.pinimg.com/736x/ff/dd/b5/ffddb5bbb6cb5028907529be521a8dad.jpg"
                                                        radius:[30]
                                                        pos_hint:{"top":1}

                                                    MDLabel:
                                                        text:"Healing Sound"
                                                        font_style:"Subtitle1"
                                                        bold:True
                                                        padding:10
                                                        pos_hint:{"top":0.68}
                                            MDCard:
                                                size_hint_y:0.2
                                                size_hint_x:0.48
                                                pos_hint:{"top":0.3,"right":0.49}
                                                md_bg_color:"white"
                                                on_press: root.play_background_sound("4")
                                                radius:[30]
                                                padding:5
                                                MDRelativeLayout:
                                                    FitImage:
                                                        source:"https://i.pinimg.com/736x/c7/3e/46/c73e46fb5e1f7916857e113e9907d4ff.jpg"
                                                        radius:[30]
                                                    MDLabel:
                                                        text:"Motivational Sound"
                                                        font_style:"Subtitle1"
                                                        bold:True
                                                        padding:10
                                                        pos_hint:{"top":0.68}      
                                                
                                            MDCard:
                                                size_hint_y:0.05
                                                size_hint_x:0.7
                                                md_bg_color:"#fff2e6"
                                                pos_hint:{"top":0.06,"right":0.9}
                                                MDRelativeLayout:
                                                    id:Msound
                                                
                                            MDIconButton:
                                                icon:"stop-circle"
                                                icon_size:40
                                                pos_hint:{"top":0.08}
                                                on_press: root.stop_sound()
                                    MDBoxLayout:
                                        size_hint_y:0.3
                                        MDRelativeLayout:
                                            FitImage:
                                                source:"C:/Users/uvais/Downloads/pimg/space.png"
                                                size_hint_y:0.5
                                                pos_hint:{"top":0.9}
                                            MDLabel:
                                                color:"black"
                                                text:"Immersing Yourself in Visualization with Affirmations"
                                                font_style:"H4"
                                                bold:True
                                                pos_hint:{"top":1.28}
                                                padding:10
                                            MDLabel:
                                                color:"black"
                                                text:"Last Step"
                                                font_style:"H6"
                                                bold:True
                                                pos_hint:{"top":1.08}
                                                padding:10
                                            MDLabel:
                                                color:"black"
                                                text:"After finishing your visualization, spend a moment expressing gratitude for what you already have and for the manifestation of your goals. This keeps your vibration high and positive."
                                                font_style:"Subtitle2"
                                                bold:True
                                                pos_hint:{"top":0.73}
                                                padding:10
                                            MDLabel:
                                                color:"black"
                                                text:"1. Find a Quiet and Comfortable Place.\n\n2. Relax Your Body and Mind.\n\n3. Plug in Your Earphones or AirPods.\n\n4. End with Gratitude."
                                                font_style:"Caption"
                                                bold:True
                                                pos_hint:{"top":0.9}
                                                padding:10
                                            
                                            MDCard:
                                                size_hint_y:0.1
                                                size_hint_x:0.9
                                                md_bg_color:"#6600ff"
                                                id:str_button
                                                MDRelativeLayout:
                                                    MDRaisedButton:
                                                        text: "Start"
                                                        md_bg_color: "#6600ff"
                                                        on_press: root.play_background_sound("ok")
                                                        on_release:root.manager.current = 'visualization_instraction'
                                                        size_hint_x:0.5
                                                        size_hint_y:0.8
                                                        pos_hint:{"top":0.5,"top":1}

                                                        

###################################################

                                                    

                        # Techniques Screen

<MyToggleButton@MDRaisedButton>:
    halign:"center"
    md_bg_color: "red"
    text_color: "#000000"
                    

<loaform>:
    name:"loaform"
    FitImage:
        id:imagery_img
        source:"https://i.pinimg.com/736x/5f/f1/b9/5ff1b94b1fc6c86dccb0996ae8621d9e.jpg"
    
        
    MDBoxLayout:
        
        orientation: 'vertical'
        spacing: dp(10)
        #pos_hint:{"top":1}
        size_hint_x:1
        size_hint_y:1
        MDCard:
            md_bg_color:"black"
            size_hint_y:0.15
            radius:[30]
            elevation:3
            
            MDRelativeLayout:
               
                MDLabel:
                    id:bot_name
                    text: "Manifest Your Desires"
                    color: "white"
                    font_style:"H5"
                    halign: "center"
                    bold:"True"
                    #pos_hint:{"right":1.06}
        MDLabel:
            text: "Before you begin, please share your goals and the challenges you're facing."
            color:"white"
            bold:"True"
            halign: "center"
            size_hint_y: None
            height: "40dp"

        MDScrollView:
                       
            MDBoxLayout:
                orientation: 'vertical'
                size_hint_y:5
                size_hint_x:1
                padding:[10]
                MDCard:
                    md_bg_color:"black"
                    radius: [40, 40, 40, 40]
                    size_hint_y:0.8
                    padding:[15]
                    MDRelativeLayout:
                        
                        Video:
                            source:"C:/Users/uvais/Downloads/pimg/g6.gif"
                            state:"play"
                            preview:None
                            volume: 0
                            allow_fullscreen: True
                            pos_hint:{"right":1}
                            options: {'eos': 'loop'}
                            size_hint_y:1
                        MDLabel:
                            text:"Your Main Goal's"
                            color:"white"
                            font_style:"H6"
                            pos_hint:{"center_y":0.95,"center_x":0.7}
                            
                        MDLabel:
                            text:"• What is the most important goal you want to manifest right now?"
                            color:"white"
                            font_style:"Subtitle1"
                            pos_hint:{"center_y":0.8,"center_x":0.54}
                        MDLabel:
                            text:"• Be clear and specific about what you desire."
                            color:"white"
                            font_style:"Subtitle1"
                            pos_hint:{"center_y":0.65,"center_x":0.54}
                        MDLabel:
                            text:"• Eample : "
                            color:"white"
                            font_style:"Subtitle1"
                            pos_hint:{"center_y":0.51,"center_x":0.54}
                        MDLabel:
                            text:"• if your goal is financial success, you might write, 'I want to earn $100,000 per year through my dream job. "
                            color:"white"
                            font_style:"Caption"
                            pos_hint:{"center_y":0.4,"center_x":0.54}
                        MDLabel:
                            text:"• If your goal is related to relationships, you could write, 'I want to build a loving, supportive partnership. "
                            color:"white"
                            font_style:"Caption"
                            pos_hint:{"center_y":0.25,"center_x":0.54}
                            
                        MDTextField:
                            id: input1
                            hint_text: "Tell us your goals"
                            mode: "fill"
                            radius: [20, 20, 20, 20]
                            size_hint_y: None
                            height: "80dp"
                            max_text_length: 50
                            line_color_normal: "white"
                            #hint_text_color:"white"
                            text_color: "white"
                            hint_text_color_normal: "white"
                       
                MDNavigationDrawerDivider:
                MDCard:
                    md_bg_color:"black"
                    radius: [40, 40, 40, 40]
                    size_hint_y:0.8
                    padding:[15]
                    MDRelativeLayout:
                        
                        Video:
                            source:"C:/Users/uvais/Downloads/pimg/g7.gif"
                            state:"play"
                            volume: 0
                            allow_fullscreen: True
                            pos_hint:{"right":1}
                            options: {'eos': 'loop'}
                            size_hint_y:1
                            preview:None
                        MDLabel:
                            text:"Why this goal is important to you?"
                            color:"white"
                            font_style:"H6"
                            pos_hint:{"center_y":0.91,"center_x":0.55}
                            
                        MDLabel:
                            text:"• Understanding why your goal is important helps us guide you better on your journey. It also helps you clarify your own motivations."
                            color:"white"
                            font_style:"Subtitle2"
                            pos_hint:{"center_y":0.71,"center_x":0.54}
                        MDLabel:
                            text:"• There’s no right or wrong answer here. Your reason is unique to you and reflects what matters most in your life."
                            color:"white"
                            font_style:"Subtitle2"
                            pos_hint:{"center_y":0.53,"center_x":0.54}
                        MDLabel:
                            text:"• For example, someone might say, 'This goal is important to me because it will make me feel more confident,' or 'It will help me provide a better future for my family.' Your answer could be similar or completely different—it's up to you."
                            color:"white"
                            font_style:"Caption"
                            pos_hint:{"center_y":0.32,"center_x":0.54}
                       
                            
                        MDTextField:
                            id: input2
                            hint_text: "tell us the importance of your goal"
                            mode: "fill"
                            radius: [20, 20, 20, 20]
                            size_hint_y: None
                            height: "80dp"
                            max_text_length: 50
                            line_color_normal: "white"
                            #hint_text_color:"white"
                            text_color: "white"
                            hint_text_color_normal: "white"
                       
                MDNavigationDrawerDivider:
                       
                MDCard:
                    md_bg_color:"black"
                    radius: [40, 40, 40, 40]
                    size_hint_y:0.8
                    padding:[15]
                    MDRelativeLayout:
                        
                        Video:
                            source:"C:/Users/uvais/Downloads/pimg/g8.gif"
                            state:"play"
                            volume: 0
                            allow_fullscreen: True
                            pos_hint:{"right":1}
                            options: {'eos': 'loop'}
                            size_hint_y:1
                            preview:None
                        MDLabel:
                            text:"What are the challenges are you're facing"
                            color:"white"
                            font_style:"H6"
                            pos_hint:{"center_y":0.93,"center_x":0.55}
                            
                        MDLabel:
                            text:"• Understanding the challenges you're facing will help us provide you with the best guidance and support to overcome them."
                            color:"white"
                            font_style:"Subtitle2"
                            pos_hint:{"center_y":0.75,"center_x":0.54}
                        MDLabel:
                            text:"• Identifying challenges is the first step to overcoming them and moving closer to your goal."
                            color:"white"
                            font_style:"Subtitle2"
                            pos_hint:{"center_y":0.59,"center_x":0.54}
                        MDLabel:
                            text:"• For example, some people might face challenges like procrastination, lack of time, or fear of failure. Others might struggle with not knowing where to start or feeling overwhelmed."
                            color:"white"
                            font_style:"Caption"
                            pos_hint:{"center_y":0.42,"center_x":0.54}
                        MDLabel:
                            text:"• It's completely okay to have challenges—everyone does. You're not alone in this, and we're here to help you find solutions."
                            color:"white"
                            font_style:"Caption"
                            pos_hint:{"center_y":0.24,"center_x":0.54}
                       
                            
                        MDTextField:
                            id: input3
                            hint_text: "Tell us your challenges"
                            mode: "fill"
                            radius: [20, 20, 20, 20]
                            size_hint_y: None
                            height: "80dp"
                            max_text_length: 50
                            line_color_normal: "white"
                            #hint_text_color:"white"
                            text_color: "white"
                            hint_text_color_normal: "white"
                       
                MDNavigationDrawerDivider:
                MDCard:
                    md_bg_color:"black"
                    radius: [40, 40, 40, 40]
                    size_hint_y:0.8
                    padding:[15]
                    MDRelativeLayout:
                        
                        Video:
                            source:"C:/Users/uvais/Downloads/pimg/g9.gif"
                            state:"play"
                            volume: 0
                            allow_fullscreen: True
                            pos_hint:{"right":1}
                            options: {'eos': 'loop'}
                            size_hint_y:1
                            
                        MDLabel:
                            text:"Describe your positive outcome if you achieve your goal"
                            color:"white"
                            font_style:"H6"
                            pos_hint:{"center_y":0.91,"center_x":0.55}
                            
                        MDLabel:
                            text:"• Visualizing the benefits of achieving your goal can inspire you and give you clarity on why it’s worth pursuing."
                            color:"white"
                            font_style:"Subtitle2"
                            pos_hint:{"center_y":0.74,"center_x":0.54}
                        MDLabel:
                            text:"• Think about how achieving this goal will make you feel and what positive changes it will bring to your life."
                            color:"white"
                            font_style:"Subtitle2"
                            pos_hint:{"center_y":0.59,"center_x":0.54}
                        MDLabel:
                            text:"• For example, achieving your goal might mean feeling healthier, more confident, or financially secure. It could also mean gaining more time for family, advancing in your career, or simply feeling happier and fulfilled.."
                            color:"white"
                            font_style:"Caption"
                            pos_hint:{"center_y":0.4,"center_x":0.54}
                        MDLabel:
                            text:"• Everyone's vision of success is unique, and there’s no right or wrong answer. This is about what matters most to you."
                            color:"white"
                            font_style:"Caption"
                            pos_hint:{"center_y":0.23,"center_x":0.54}
                       
                            
                        MDTextField:
                            id: input4
                            hint_text: "Tell us your positive outcome"
                            mode: "fill"
                            radius: [20, 20, 20, 20]
                            size_hint_y: None
                            height: "80dp"
                            max_text_length: 50
                            line_color_normal: "white"
                            #hint_text_color:"white"
                            text_color: "white"
                            hint_text_color_normal: "white"
                       
                MDNavigationDrawerDivider:
                MDCard:
                    md_bg_color:"black"
                    radius: [40, 40, 40, 40]
                    size_hint_y:0.8
                    padding:[15]
                    MDRelativeLayout:
                        
                        Video:
                            source:"C:/Users/uvais/Downloads/pimg/g10.gif"
                            state:"play"
                            volume: 0
                            allow_fullscreen: True
                            pos_hint:{"right":1}
                            options: {'eos': 'loop'}
                            size_hint_y:1
                        MDLabel:
                            text:"What small action can you take today?"
                            color:"white"
                            font_style:"H6"
                            pos_hint:{"center_y":0.91,"center_x":0.55}
                            
                        MDLabel:
                            text:"• Big goals are achieved through small, meaningful steps. Taking action today can set the foundation for your success."
                            color:"white"
                            font_style:"Subtitle2"
                            pos_hint:{"center_y":0.74,"center_x":0.54}
                        MDLabel:
                            text:"• Every action, no matter how small, brings you closer to your goal. It’s about progress, not perfection."
                            color:"white"
                            font_style:"Subtitle2"
                            pos_hint:{"center_y":0.59,"center_x":0.54}
                        MDLabel:
                            text:"• For example, if your goal is to improve your health, you might drink more water or take a short walk. If it’s about learning a new skill, you might watch a tutorial or practice for 10 minutes."
                            color:"white"
                            font_style:"Caption"
                            pos_hint:{"center_y":0.42,"center_x":0.54}
                        MDLabel:
                            text:"• Remember, small actions lead to big changes. The most important thing is to start."
                            color:"white"
                            font_style:"Caption"
                            pos_hint:{"center_y":0.25,"center_x":0.54}
                       
                            
                        MDTextField:
                            id: input5
                            hint_text: "Tell us your today's action"
                            mode: "fill"
                            radius: [20, 20, 20, 20]
                            size_hint_y: None
                            height: "80dp"
                            max_text_length: 50
                            line_color_normal: "white"
                            #hint_text_color:"white"
                            text_color: "white"
                            hint_text_color_normal: "white"
                       
                MDNavigationDrawerDivider:
                
                MDRaisedButton:
                    text: "Submit"
                    size_hint_y: None
                    height: "50dp"
                    pos_hint:{"center_x":0.5}
                    on_release:root.submit_data()
                    
<visualization_instraction>
    name:"visualization_instraction"
    FitImage:
        source:"https://i.pinimg.com/736x/dd/37/1b/dd371bb36b3bac2aa0eb1f3a14049651.jpg"
    MDBoxLayout:
        orientation: "vertical"
        spacing: "10dp"
        padding: "20dp"
        
        MDRelativeLayout:
            MDLabel:
                id: song_label
                text: "Visualization with Affirmation "
                theme_text_color: "Custom"
                halign: "center"
                font_style: "H5"
                bold:True
                pos_hint:{"top":1.4,"right":1}
            FitImage:
                id: album_image
                pos_hint:{"top":0.78,"right":0.9}
                halign:"center"
                source: "https://i.pinimg.com/736x/dd/37/1b/dd371bb36b3bac2aa0eb1f3a14049651.jpg"
                radius:[200,200]
                size_hint: None, None
                size: 250, 250

                canvas.before:
                    PushMatrix
                    Rotate:
                        angle: app.angle  # Now correctly linked
                        origin: self.center
                canvas.after:
                    PopMatrix
            MDProgressBar:
                id: progress_bar
                value: 0
                color: "#6600ff"
                size_hint_y:0.05
                pos_hint:{"top":0.33}
            MDBoxLayout:
                orientation: "horizontal"
                size_hint_y: None
                height: "50dp"
                spacing: "10dp"
                padding: "20dp"
                pos_hint:{"top":0.3}
                MDRelativeLayout:
                    MDLabel:
                        id: current_time
                        text: "00:00"
                        theme_text_color: "Custom"
                        text_color: 1, 1, 1, 1
                        halign: "left"
                       
                    MDLabel:
                        id: total_time
                        text: "00:00"
                        theme_text_color: "Custom"
                        text_color: 1, 1, 1, 1
                        halign: "right"
                        
            MDFloatingActionButton:
                id: play_button
                md_bg_color:"#6600ff"
                icon: app.play_icon  # Initially "play", changes dynamically
                pos_hint: {"center_x": 0.5}
                on_release: root.toggle_audio()

                        


                
                

                
                            

                    
                            
                        
                            

                            